package gr.ppzglou.food

const val FOOD_PREFS = "FOOD"
const val AUTH_UUID = "AUTH_UUID"
const val AUTH_IS_VERIFIED = "AUTH_IS_VERIFIED"
const val BRAIN_TREE_TOKEN = "BRAIN_TREE_TOKEN"

const val AUTHENTICATION_PIN_TIME = "AUTHENTICATION_PIN_TIME"
const val AUTHENTICATION_PIN_COUNT = "AUTHENTICATION_PIN_COUNT"

//themes
const val THEME_MODE = "THEME_MODE"
const val DARK_MODE = "DARK_MODE"
const val LIGHT_MODE = "LIGHT_MODE"
const val SYSTEM_MODE = "SYSTEM_MODE"

//error codes
const val ERROR_PIN_OF_USER_NOT_EXIST = 3001
const val ERROR_PIN_OF_USER_IS_WRONG = 3002

const val ERROR_NO_INTERNET = 1111
const val ERROR_GENERAL = 400
const val ERROR_MEMBER_EXIST = 1100
const val ERROR_NOT_EMAIL_VALIDATED = 1200
const val ERROR_NOT_MEMBER_EXIST = 1300
const val ERROR_WRONG_PASSWORD = 1400
const val ERROR_MEMBER_HAS_DISABLED = 1500
const val ERROR_MEMBER_HAS_BLOCKED = 1600
const val ERROR_TOO_MANY_REQUESTS = 1700
const val ERROR_INVALID_CREDENTIALS = 1800
const val ERROR_WRONG_OTP_CODE = 1900
const val ERROR_PHONE_IS_LINKED_WITH_OTHER_ACCOUNT = 2000

